"""SSC CGL Tier-1 syllabus chapters by subject and priority."""

SYLLABUS_DATA = [
    {
        "slug": "quant",
        "name": "Quantitative Aptitude",
        "short_name": "Quant",
        "color": "blue",
        "sort_order": 1,
        "chapters": [
            ("Percentage", "very_high", 1),
            ("Ratio and Proportion", "very_high", 2),
            ("Profit and Loss", "very_high", 3),
            ("Simple Interest", "very_high", 4),
            ("Compound Interest", "very_high", 5),
            ("Average", "very_high", 6),
            ("Time and Work", "very_high", 7),
            ("Time Speed Distance", "very_high", 8),
            ("Algebra", "very_high", 9),
            ("Geometry", "very_high", 10),
            ("Mensuration", "very_high", 11),
            ("Trigonometry", "very_high", 12),
            ("Number System", "high", 13),
            ("Simplification", "high", 14),
            ("HCF & LCM", "high", 15),
            ("Data Interpretation", "high", 16),
            ("Mixture & Alligation", "high", 17),
            ("Coordinate Geometry", "medium", 18),
            ("Partnership", "medium", 19),
            ("Boat & Stream", "medium", 20),
            ("Pipe & Cistern", "medium", 21),
            ("Surds & Indices", "low", 22),
            ("Heights & Distances", "low", 23),
        ],
    },
    {
        "slug": "english",
        "name": "English Comprehension",
        "short_name": "English",
        "color": "purple",
        "sort_order": 2,
        "chapters": [
            ("Error Detection", "very_high", 1),
            ("Cloze Test", "very_high", 2),
            ("Reading Comprehension", "very_high", 3),
            ("Synonyms & Antonyms", "very_high", 4),
            ("Vocabulary", "very_high", 5),
            ("One Word Substitution", "very_high", 6),
            ("Idioms & Phrases", "very_high", 7),
            ("Active Passive Voice", "high", 8),
            ("Direct Indirect Speech", "high", 9),
            ("Sentence Improvement", "high", 10),
            ("Fill in the Blanks", "high", 11),
            ("Para Jumbles", "medium", 12),
            ("Spelling Correction", "medium", 13),
            ("Foreign Words", "low", 14),
        ],
    },
    {
        "slug": "reasoning",
        "name": "General Intelligence & Reasoning",
        "short_name": "Reasoning",
        "color": "orange",
        "sort_order": 3,
        "chapters": [
            ("Analogy", "very_high", 1),
            ("Classification", "very_high", 2),
            ("Series", "very_high", 3),
            ("Coding Decoding", "very_high", 4),
            ("Blood Relation", "very_high", 5),
            ("Direction Sense", "very_high", 6),
            ("Syllogism", "very_high", 7),
            ("Seating Arrangement", "very_high", 8),
            ("Venn Diagram", "very_high", 9),
            ("Non-Verbal Reasoning", "high", 10),
            ("Mirror Image", "high", 11),
            ("Paper Folding", "high", 12),
            ("Dice", "high", 13),
            ("Embedded Figures", "high", 14),
            ("Statement Conclusion", "medium", 15),
            ("Statement Assumption", "medium", 16),
            ("Cause and Effect", "medium", 17),
            ("Cube and Cuboid", "low", 18),
            ("Water Image", "low", 19),
        ],
    },
    {
        "slug": "gk",
        "name": "General Awareness",
        "short_name": "GK",
        "color": "green",
        "sort_order": 4,
        "chapters": [
            ("Current Affairs", "very_high", 1),
            ("Static GK", "very_high", 2),
            ("History", "very_high", 3),
            ("Geography", "very_high", 4),
            ("Polity", "very_high", 5),
            ("Economics", "very_high", 6),
            ("Science", "high", 7),
            ("Biology", "high", 8),
            ("Physics", "high", 9),
            ("Chemistry", "high", 10),
            ("Computer Awareness", "medium", 11),
            ("Important Schemes", "medium", 12),
            ("Books & Authors", "medium", 13),
            ("Art & Culture", "low", 14),
        ],
    },
]

PRIORITY_ORDER = {"very_high": 0, "high": 1, "medium": 2, "low": 3}

PRIORITY_LABELS = {
    "very_high": "Very High Priority",
    "high": "High Priority",
    "medium": "Medium Priority",
    "low": "Low Priority",
}
